# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    pip install yt-dlp opencv-python-headless numpy

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
# COPY . /app
COPY capture_and_detect.py /app/

# Run the application
CMD ["python", "capture_and_detect.py"]
